### ISSUE TITLE
line 63 and line 73 Error

### ISSUE THREAD

**Issue by Huibuh2010** [TebbaaX/Katana#19]
Hello, i like to try ur tool but it comes error.

Can u plz help me to solve it? i installed required.

`Traceback (most recent call last):
  File "/home/Katana-master/kds.py", line 63, in <module>
    from Modes import Gmode
  File "/home/Katana-master/Modes/Gmode.py", line 73, in <module>
    for gamma in search(query, tld=beta, num=10 , stop=95 , pause=2): 
TypeError: search() got an unexpected keyword argument 'tld'`

i see its line with gmode module but if i try to install 

python3 -m pip install gmode  
ERROR: Could not find a version that satisfies the requirement gmode
ERROR: No matching distribution found for gmode

**Comment by TebbaaX** [comment]
Please do `cd Katana`  and **Run the tool in Directory** 
also i implemented a simple fix for the tld (TLD) issue. 
Thanks for flagging the issue 👍
