### ISSUE TITLE
Tor66 is down

### ISSUE THREAD

**Issue by ramixix** [TebbaaX/Katana#22]
When using the **"-t :tor mode"** flag, the program crashes for every query I make, this is because the Tor66 service is down and is no longer running.

 **http://tor77orrbgejplwp.onion/search?q=" + xquery + "&sorttype=rel&page=1" ==> Invalid Onionsite Address**

**Comment by ramixix** [comment]
By the way I could be wrong, _**http://tor66sewebgixwhcqfnp5inzp5x5uohhdy3kvtnyfxc2e5mxiuh34iid.onion/search?q=**_  if this be the link to tor66 search engine then it works fine but the link you are using is not working

**Comment by TebbaaX** [comment]
Link changed, Thank you!
